### ISSUE TITLE
网站做了防盗处理 ，referer头域要传入套图地址，不能写死了。

### ISSUE THREAD

**Issue by Lulu-Miao** [chenjiandongx/mzitu#10]
https://github.com/chenjiandongx/mzitu/blob/0de230cb4ef8b59db91453504dba70bbe48185b4/mzitu.py#L60

**Comment by Lulu-Miao** [comment]
好像和issue#8重复了。。。

**Comment by chenjiandongx** [comment]
嗯 那你自己修改一下本地代码就可以了
