### ISSUE TITLE
现在爬一次就会被网站封

### ISSUE THREAD

**Issue by ghost** [chenjiandongx/mzitu#18]
第一次测试可以爬取成功，再次爬取就会被网站封掉，显示

HTTPConnectionPool(host='www.mzitu.com', port=80): Max retries exceeded with url: /page/1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2dd56e06d8>, 'Connection to www.mzitu.com timed out. (connect timeout=10)'))

**Comment by chenjiandongx** [comment]
@sshnii 解决这个问题有助于你提升反爬技巧。So, try to fix it.

**Comment by ghost** [comment]
> @sshnii 解决这个问题有助于你提升反爬技巧。So, try to fix it.

哈哈哈，我研究研究
