### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by kennel2014** [chenjiandongx/mzitu#6]
本人环境 win32+python3.5
1.请问你代码中是不是没有图片重复检测？
2.代码没法直接运行，会报错，BeautifulSoup4、lxml 至少缺这两个库，还有一个库也缺，忘记名字了....
3.安装完代码提示报错的三个库，运行程序，下载下来的图片有点问题....我不晓得是网站做了保护还是代码本身的问题
![l1ds05grryw1u zpm_ tg42](https://user-images.githubusercontent.com/6291886/29008733-6d5bc37a-7b4e-11e7-9846-4b4c669b5379.png)
![qq 20170807085900](https://user-images.githubusercontent.com/6291886/29008732-6d539f4c-7b4e-11e7-8c84-8fb0b4c1aee4.jpg)

**Comment by torchcode** [comment]
增加了反盗链，应该在头文件headers中，增加Referer

**Comment by chenjiandongx** [comment]
@kennel2014 套图是会有去重的 图片名字相同但是他们分别在不同的文件夹 这个是没有问题的 至于程序本身 我好久没运行了 不然你按照 @torchcode 说的试试？

**Comment by kennel2014** [comment]
已搞定
